### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by greysoftcrazy** [frankhale/nw-edge-example#4]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with nw-edge-example. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable nw-edge-example on @Sourcegraph by going to https://sourcegraph.com/github.com/frankhale/nw-edge-example and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by frankhale** [comment]
Judging by the recent activity in Edge.js it looks like it finally compiles with new versions of Node. This is good news, for the longest time Edge was basically dead to the world. I'll try getting this code working with the recent version of Node-Webkit. If that succeeds I'll do what you ask, if not I'll decline as there would be no new updates to this code. This is strictly incumbent on Edge working with the latest version of Node-Webkit.

**Comment by frankhale** [comment]
In other words I don't see any reason to do what you ask unless Edge can finally work with the latest version of Node-Webkit (aka NWJS). I'll try using the latest Edge with the latest NWJS this weekend.

**Comment by frankhale** [comment]
Good news is that Edge definitely compiles against new versions of iojs. I just compiled it against 1.5.0. Now I'm trying to see how to get it to work in Node-Webkit. It appears as though Node-Webkit (aka nwjs) 0.12 is using iojs 1.2 but I'm having some difficulty in nwjs land trying to compile it. I'll report back if I can get it to work. If that's the case then this example may be useful again.

**Comment by frankhale** [comment]
Not sure what's going on. I installed node 0.12. I'm rebuilding Edge using nw-gyp, everything works but nwjs 0.12 reports in the Chrome dev tools that the module was not built using the right version of node which it reports needs v1.2.0 so it cannot load it. Makes no sense.

**Comment by frankhale** [comment]
I tried 32 bit and 64 bit, I have a sane build environment. Edge appears to be building fine. nwjs is not loading the module. I'll try digging more into it.

**Comment by frankhale** [comment]
Moving this build related stuff here https://github.com/frankhale/nw-edge-example/issues/5

**Comment by frankhale** [comment]
Unfortunately Sourcegraph incorrectly determines that this repo is C# when infact it's really JavaScript which a C# source file included for illustration. I'm closing this because of that error.

```
Probably unsupported. Sourcegraph doesn't support C#, which appears to be this repository's primary language. The supported languages are Python, Go, Ruby, and JavaScript (node.js with package.json only).
To attempt to use Sourcegraph's code browsing and code review features on this repository anyway, enable this repository.
```
