### ISSUE TITLE
Attempt to make this work with nwjs 0.12

### ISSUE THREAD

**Issue by frankhale** [frankhale/nw-edge-example#5]
The latest version of Edge compiles against node 0.12.x so this should be theoretically possible to make work.

**Comment by frankhale** [comment]
w00t! I got it to work. LOLOLOL! But it requires hacking lib/edge.js and changing the versionMap to recognize the reported node version as 1.2.0

```javascript
[ /1.2.0/, '0.12.0' ]
```

**Comment by frankhale** [comment]
It works with nwjs 0.12 x64 via af9380140ff465aba1bf610065107daad506f97b

**Comment by frankhale** [comment]
Note, I've included the node_modules/edge folder in the repo. Should be able to clone and run on x64 Windows without doing any recompiling whatsoever.

**Comment by jmorvan** [comment]
Doesnt work for me. After nw-gyp i get:

Uncaught Error: %1 is not a valid Win32 application.
C:\Project\node_modules\edge\lib\native\win32\x64\0.12.0\edge.node

Any clue?

**Comment by frankhale** [comment]
Do you have Python installed?

**Comment by jmorvan** [comment]
yes, and it all builds fine

**Comment by frankhale** [comment]
Okay so you ran nw-gyp to configure the module and then you built the module? At what point is this happening?

```
Uncaught Error: %1 is not a valid Win32 application.
C:\Project\node_modules\edge\lib\native\win32\x64\0.12.0\edge.node
```

**Comment by jmorvan** [comment]
when I require:
```var edge = require('edge');```

**Comment by frankhale** [comment]
So you see that message in the NW devtools console window? Can you provide the code for your app so I can take a look and see if I can figure out what is going on?

**Comment by jmorvan** [comment]
Actually my app is just a blank nw.

Further into the error, it seems to crash on line 42 of edge.js:

```edge = require(edgeNative);```

on module.load

**Comment by frankhale** [comment]
Maybe it's one or the other, either the Edge module is compiled for 32 bit and trying to load in a 64 bit NW or vice versa. Both must be the same. If the Edge module won't load into NW there isn't very many other things that can be the problem. 

I've provided a 64 bit compiled Edge module in this repo that you are free to try out. Needs a 64 bit NW to run the project.

**Comment by jmorvan** [comment]
Ok I got it to work by copying the entire lib folder from your project. I was just copying the .node before.
Wonder what more there is is to your lib thatst not in mine....

Thanks for your time

**Comment by frankhale** [comment]
Could be you forgot this step?

Once the build finishes, the new module will be in:

```
c:\my-app\node_modules\edge\build\Release
```

Copy edge.node to: (depending on your architecture, I built against x64)

```
c:\my-app\node_modules\edge\lib\native\win32\x64\0.12.0
```

**Comment by jmorvan** [comment]
Nope, I did this too.

**Comment by frankhale** [comment]
Maybe when you built Edge it did not build for 64 bit. Maybe it built a 32 bit module? Seems plausible given that NW couldn't load it and complained that it wasn't valid. A completely different error occurs when the module is not built properly for NW (ie by using nw-gyp instead of node-gyp).

**Comment by zs-zs** [comment]
Hi,

I did the same steps and I have exactly the same problem. However, it works if I use the edge folder from your project. It seems that your build configuration is somehow a bit different than ours.
How did you configure nw-gyp to build a 64 bit module?

**Comment by frankhale** [comment]
I'm using the Visual Studio 2013 command prompt so that all the build tools are in the environment. It's building 64 bit binaries by default, I did not have to specifically instruct it to do so.

**Comment by frankhale** [comment]
Here is the path on my system for the Visual Studio 2013 command prompt:

```
C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\VsDevCmd.bat
```

When you run the following commands do you see anything suggesting it's building 32 bit binaries?

```
nw-gyp configure --target=v0.12.0 --msvs_version=2013
nw-gyp build
```

**Comment by frankhale** [comment]
@zs-zs, were you able to compile a 64 bit binary of Edge that works in nw.js?
